# Generated by Django 3.2.7 on 2021-09-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='geratezeitstempel',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='level',
            name='seriennummer',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
